### PR TITLE
Final touches

### PR DESCRIPTION
**Pull request by carloso0114**
Style a little bit of the table to make it scrollable.

This project is using async and awaits functions.

### CODE REVIEW

**Review by MahmoudBakr23 — COMMENTED** [review]
# Hi @carloso0114 😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- Please make sure to fix all the linter errors before submitting for a review 🙏 

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

**Comment by carloso0114** [comment]
> # Hi @carloso0114 😃,
> As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.
> 
> ## **Invalid Submission**
> * Please make sure to fix all the linter errors before submitting for a review 🙏
> 
> _Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
> 
> _Invalid Code Review Request does not count into the code reviews limit._

My bad! It's already fixed.

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
Hi @carloso0114, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Your layout is matching with the [wireframe](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/images/leaderboard_wireframe.png) design.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] Something to improve on the readme file, is to talk about the API and add instructions about how to use it. Please, include all that's needed for running the app with the API(s) it consumes. It should have instructions about where and how to generate any necessary keys, credentials, how to set, store, and generate them (if necessary). You can reference [this link](https://www.notion.so/microverse/Leaderboard-API-service-24c0c3c116974ac49488d4eb0267ade3) as well.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- As I have seen this [comment](https://github.com/carloso0114/leaderboard-Js/pull/2#pullrequestreview-718755346), I am inviting you to please add `start` script to your `package.json` file so that we can easily start the live server of your project.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @carloso0114 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

sassy

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
